@host=http://localhost:5013/api
@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Mzg4NGQxNi00NmEzLTQzNDctOWMzYS1hZGRmNDI3ZDM4YjQiLCJlbWFpbCI6ImFkZXYwOEBvdXRsb29rLmNvbSIsImdpdmVuX25hbWUiOiJBbnRob255IiwiZmFtaWx5X25hbWUiOiJEZXZpbGxlIiwianRpIjoiYTI4ZTUwNWMtZTU5Yi00MzQxLTgyMTgtN2I4YzcyOWEwNmQ4IiwiZXhwIjoxNzAxMTA1Nzk0LCJpc3MiOiJQaXp6YU1hbmFnZW1lbnQiLCJhdWQiOiJQaXp6YU1hbmFnZW1lbnQifQ.fWHgHOOXLn_aU2elbldorNOMOfxt5dbmCCay0ZKNhqROR4wRTt_u-ORLntXdJTacqzQZr4WcDAVAbkCnepTo0g


GET {{host}}/recipes/ratings/F127A49D-167B-4726-BA53-6DBA1880C485
Authorization: Bearer {{token}}
Content-Type: application/json
