@host=http://localhost:5013/api
@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Mzg4NGQxNi00NmEzLTQzNDctOWMzYS1hZGRmNDI3ZDM4YjQiLCJlbWFpbCI6ImFkZXYwOEBvdXRsb29rLmNvbSIsImdpdmVuX25hbWUiOiJBbnRob255IiwiZmFtaWx5X25hbWUiOiJEZXZpbGxlIiwianRpIjoiZGM0YTc3YWYtM2VlZC00ZGYzLWFjOTgtMDZmZjFmZWE4ZmI1IiwiZXhwIjoxNzAwODIwMTI2LCJpc3MiOiJQaXp6YU1hbmFnZW1lbnQiLCJhdWQiOiJQaXp6YU1hbmFnZW1lbnQifQ.gA9KTzDg4T7k1yceLjWaSzCD55z4TaQUMTqSnq_hdvJ4EmJD_yvQQtUaD9IOQz3Aa978QC52Mj_K26vHAzkb1Q


GET {{host}}/auth
Authorization: Bearer {{token}}
Content-Type: application/json
