@host=http://localhost:5013/api
@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYjk2MGMwNC0xZTc3LTRjOWMtOWE0My0zNGM1MGQ4ZDA1YzkiLCJlbWFpbCI6ImFkZXYwMDhAb3V0bG9vay5jb20iLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiOTE0NGM0MGUtMTIwNS00ZWI3LTg3NDUtY2Q3ZWRlNmE1OGM0IiwiZXhwIjoxNzAwOTM0NzkxLCJpc3MiOiJQaXp6YU1hbmFnZW1lbnQiLCJhdWQiOiJQaXp6YU1hbmFnZW1lbnQifQ.dwPcYQY2KX-Se29wk8PLqxEF5jcXlBNY72IaRFTvDw5hKCXHJ5zl3s9FahPPoEkqbC4qgA387iN-FCgmE_wA1A


GET {{host}}/recipes/rating/F127A49D-167B-4726-BA53-6DBA1880C485
Authorization: Bearer {{token}}
Content-Type: application/json
